---
  - name: Package Manager Cache
    ansible.builtin.package:
      update_cache: yes

   - name: Install Apache web server
     ansible.builtin.package:
      name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      state: present

   - name: Start and enable Apache service
     ansible.builtin.service:
       name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
       state: started
       enabled: yes
